FROM python:3.11


WORKDIR /code


COPY requirements.txt /code/requirements.txt


RUN pip install --upgrade pip


RUN pip install -r /code/requirements.txt


COPY . /code/


WORKDIR /code/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "90"]



